config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :productos
  devise_for :users
  root to: 'pagprincipal#index'
  get '/armatuskate', to:'welcome#armatuskate1'
  get '/armatuskate/elegir', to: 'welcome#index'
  get '/pedidosubido', to: 'pedidosubido#index'
  get '/quienessomos', to: 'quienessomos#index'
  get '/verproductos', to: 'verproductos#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pedido.rb
class Pedido < ApplicationRecord
end

app/models/producto.rb
class Producto < ApplicationRecord

    validates :nombre, presence: true
    validates :precio, presence: true
    validates :marca, presence: true
    validates :tipo, presence: true
    validates :img, presence: true

    has_one_attached :img
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pagprincipal_controller.rb
class PagprincipalController < ApplicationController
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: %i[ show edit update destroy ]

  # GET /pedidos or /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1 or /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos or /pedidos.json
  def create
    #@pedido = Pedido.new(pedido_params)
    carro = JSON.parse(params[:carro])

    @pedido = Pedido.new(
      nombre: params[:nombre],
      tabla: carro[0],
      trucks: carro[1],
      ruedas: carro[2],
      rulemanes: carro[3],
      lija: carro[4],
      hardware: carro[5]
    )

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to pedidosubido_url }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1 or /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to pedido_url(@pedido), notice: "Pedido was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1 or /pedidos/1.json
  def destroy
    @pedido.destroy

    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: "Pedido was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_params
      params.require(:pedido).permit(:tabla, :trucks, :ruedas, :rulemanes, :lija, :hardware, :nombre)
    end
end

app/controllers/pedidosubido_controller.rb
class PedidosubidoController < ApplicationController
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: %i[ show edit update destroy ]

  # GET /productos or /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1 or /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos or /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to productos_path, notice: "Producto creado correctamente." }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1 or /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to productos_path, notice: "Producto editado correctamente." }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1 or /productos/1.json
  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy

    respond_to do |format|
      format.html { redirect_to productos_url, notice: "Producto eliminado correctamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def producto_params
      params.require(:producto).permit(:nombre, :precio, :marca, :tipo, :img)
    end
end

app/controllers/quienessomos_controller.rb
class QuienessomosController < ApplicationController
end

app/controllers/verproductos_controller.rb
class VerproductosController < ApplicationController

    before_action do
        ActiveStorage::Current.url_options = {
          protocol: request.protocol,
          host: request.host,
          port: request.port
        }
      end
      
    def index
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action do
    ActiveStorage::Current.url_options = {
      protocol: request.protocol,
      host: request.host,
      port: request.port
    }
  end
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pagprincipal_helper.rb
module PagprincipalHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/pedidosubido_helper.rb
module PedidosubidoHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/quienessomos_helper.rb
module QuienessomosHelper
end

app/helpers/verproductos_helper.rb
module VerproductosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compra Skater</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'main/logo.png', sizes: '32x32', type: 'image/png' %>

    <!-- Bootstrap -->
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">

    <style type="text/css">
        .btn-nav{
            display: inline-block;
        }
    </style>
    <%= javascript_include_tag '/javascript/custom' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>

app/views/pagprincipal/index.html.erb
<%= render "welcome/navbar" %>

<body>
    <!--PRODUCTO DESTACADO-->
        <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                <%= image_tag("main/skate-banner-2.gif", :alt => "...", :class => "d-block w-100") %>
                </div>
                <div class="carousel-item">
                <%= image_tag("main/banner.gif", :alt => "...", :class => "d-block w-100") %>
                </div>
                <div class="carousel-item">
                <%= image_tag("main/santa-cruz-banner.jpg", :alt => "...", :class => "d-block w-100") %>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
</body>

<%= render "welcome/footer" %>

app/views/pedidos/_form.html.erb
<%= form_with(model: pedido) do |form| %>
  <% if pedido.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
        <% pedido.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tabla, style: "display: block" %>
    <%= form.text_field :tabla %>
  </div>

  <div>
    <%= form.label :trucks, style: "display: block" %>
    <%= form.text_field :trucks %>
  </div>

  <div>
    <%= form.label :ruedas, style: "display: block" %>
    <%= form.text_field :ruedas %>
  </div>

  <div>
    <%= form.label :rulemanes, style: "display: block" %>
    <%= form.text_field :rulemanes %>
  </div>

  <div>
    <%= form.label :lija, style: "display: block" %>
    <%= form.text_field :lija %>
  </div>

  <div>
    <%= form.label :hardware, style: "display: block" %>
    <%= form.text_field :hardware %>
  </div>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pedidos/_pedido.html.erb
<div id="<%= dom_id pedido %>">
  <p>
    <strong>Tabla:</strong>
    <%= pedido.tabla %>
  </p>

  <p>
    <strong>Trucks:</strong>
    <%= pedido.trucks %>
  </p>

  <p>
    <strong>Ruedas:</strong>
    <%= pedido.ruedas %>
  </p>

  <p>
    <strong>Rulemanes:</strong>
    <%= pedido.rulemanes %>
  </p>

  <p>
    <strong>Lija:</strong>
    <%= pedido.lija %>
  </p>

  <p>
    <strong>Hardware:</strong>
    <%= pedido.hardware %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= pedido.nombre %>
  </p>

</div>

app/views/pedidos/edit.html.erb
<% if user_signed_in? %>
<h1>Editing pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Show this pedido", @pedido %> |
  <%= link_to "Back to pedidos", pedidos_path %>
</div>
<% end %>

app/views/pedidos/index.html.erb
<!--
<p style="color: green"><%= notice %></p>

<h1>Pedidos</h1>

<div id="pedidos">
  <% @pedidos.each do |pedido| %>
    <%= render pedido %>
    <p>
      <%= link_to "Show this pedido", pedido %>
    </p>
  <% end %>
</div>

<%= link_to "New pedido", new_pedido_path %>
-->

<%= render "welcome/navbar" %>

<% if user_signed_in? %>

<div class="container-xl">
    <div class="row">
      <div class="col-md-6 col-sm-12 mx-auto">
        <h1 style="padding-top: 2%;">Administrar Pedidos</h1>
      </div>
      <div class="col-md-6 col-sm-12 mx-auto d-grid gap-2 d-md-flex justify-content-md-end" style="padding-top: 1%;">
        <!--<%= link_to "Agregar Pedido", new_pedido_path, class: "btn btn-nav btn-light btn-outline-dark" %>-->
      </div>
    </div>

    <% if flash[:error].present? %>
      <p style="color: red"><%= flash[:error] %></p>
    <% end %>

    <% if flash[:success].present? %>
      <p style="color: green"><%= flash[:success] %></p>
    <% end %>

    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#id</th>
          <th scope="col">Nombre del Cliente</th>
          <th scope="col">Tabla</th>
          <th scope="col">Trucks</th>
          <th scope="col">Ruedas</th>
          <th scope="col">Rulemanes</th>
          <th scope="col">Lija</th>
          <th scope="col">Hardware</th>
        </tr>
      </thead>
      <tbody>
        <% @pedidos.each do |pedido| %>
          <tr>
            <th scope="row"><%= pedido.id %></th>
            <td><%= pedido.nombre %></td>
            <td><%= pedido.tabla %></td>
            <td><%= pedido.trucks %></td>
            <td><%= pedido.ruedas %></td>
            <td><%= pedido.rulemanes %></td>
            <td><%= pedido.lija %></td>
            <td><%= pedido.hardware %></td>

            <td>
              <!--<%= link_to "Editar", edit_pedido_path(pedido), class: "btn btn-primary" %>-->
              <%= button_to "Eliminar", pedido_path(pedido), method: :delete, data: { confirm: '¿Estás seguro de querer borrar este artículo?' }, class: "btn btn-danger", remote: true %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

<% else %>
  <p>Por favor, ingrese sesión como administrador</p>
<% end %>

<%= render "welcome/footer" %>

app/views/pedidos/new.html.erb
<% if user_signed_in? %>
<h1>New pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Back to pedidos", pedidos_path %>
</div>
<% end %>

app/views/pedidos/show.html.erb
<% if user_signed_in? %>
<p style="color: green"><%= notice %></p>

<%= render @pedido %>

<div>
  <%= link_to "Edit this pedido", edit_pedido_path(@pedido) %> |
  <%= link_to "Back to pedidos", pedidos_path %>

  <%= button_to "Destroy this pedido", @pedido, method: :delete %>
</div>

<% end %>

app/views/pedidosubido/index.html.erb
<%= render "welcome/navbar" %>

    <div class="container-xl" style="padding-top: 1%">
        <div class='row'>
            <h1>Muchas gracias por tu pedido!</h1>
            <h4>Tu pedido fue enviado y registrado con éxito. Acercate a la sucursal a realizar el pago y es tuyo.</h4>
            <div class = 'd-flex justify-content-center align-items-center'>
                <%= image_tag("main/build-skateboard", :alt => "...", :class => "img-fluid banner") %>
            </div>        
        </div>
    </div>

<%= render "welcome/footer" %>

app/views/productos/_form.html.erb
<!--
<%= form_with(model: producto) do |form| %>
  <% if producto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
        <% producto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :precio, style: "display: block" %>
    <%= form.text_field :precio %>
  </div>

  <div>
    <%= form.label :marca, style: "display: block" %>
    <%= form.text_field :marca %>
  </div>

  <div>
    <%= form.label :tipo, style: "display: block" %>
    <%= form.text_field :tipo %>
  </div>

  <div>
    <%= form.label :img, style: "display: block" %>
    <%= form.text_field :img %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
-->

  <% if user_signed_in? %>
    <div class="container-sm" style="padding-top: 1%;">

      <% if producto.errors.any? %> <!-- Mostrar errores -->
        <div class="alert alert-danger">
          <h4>Error:</h4>
          <ul>
            <% producto.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row">

        <div class="col-md-4 col-sm-12 mx-auto">
          <%= image_tag('main/imgPlaceHolder.png', class: 'rounded', style: 'width: 100%; border: 1px solid black;', alt: 'productImg') %>
        </div>

        <div class="col-md-8 col-sm-12 mx-auto">
          <%= form_with(model: producto) do |form| %>

            <p style="color: red"><%= flash[:error] %></p>
            <p style="color: green"><%= flash[:success] %></p>

            <div class="form-group">
              <label style="font-size: 20px">Nombre del producto</label>
              <%= form.text_field :nombre, class: 'form-control', placeholder: 'Ingrese el nombre del producto' %>
            </div>

            <br>
            <div class="form-group">
              <label style="font-size: 20px">Precio</label>
              <%= form.number_field :precio, class: 'form-control', placeholder: 'Ingrese el precio' %>
            </div>

            <br>
            <div class="form-group">
              <label style="font-size: 20px">Marca</label>
              <%= form.text_field :marca, class: 'form-control', placeholder: 'Ingrese la marca' %>
            </div>

            <br>
            <div class="form-group">
              <label style="font-size: 20px">Tipo</label>
              <%= form.select :tipo, options_for_select(['tabla', 'rulemanes', 'ruedas', 'trucks', 'hardware', 'lija', 'skateCompleto']), {}, class: 'form-select', placeholder: 'Seleccionar...' %>
            </div>

            <br>
            <div class="form-group">
              <label style="font-size: 20px">Imagen</label>
              <%= form.file_field :img, class: 'form-control form-control-sm', id: 'formFile', style: 'font-size: 20px' %>
            </div>

            <br>
            <button type="submit" class="btn btn-dark" name="submit" value="Subir Archivos">Enviar</button>

          <% end %>
        </div>
      </div>
    </div>
  <% else %>
    <p>Usted no ha ingresado como administrador. Haga click <%= link_to 'aquí', new_user_session_path %> para hacerlo</p>
  <% end %>

app/views/productos/index.html.erb
<%= render "welcome/navbar" %>

<% if user_signed_in? %>
  <div class="container-xl">
    <div class="row">
      <div class="col-md-6 col-sm-12 mx-auto">
        <h1 style="padding-top: 2%;">Administrar Productos</h1>
      </div>
      <div class="col-md-6 col-sm-12 mx-auto d-grid gap-2 d-md-flex justify-content-md-end" style="padding-top: 1%;">
        <%= link_to "Agregar Productos", new_producto_path, class: "btn btn-nav btn-light btn-outline-dark" %>
      </div>
    </div>

    <% if flash[:error].present? %>
      <p style="color: red"><%= flash[:error] %></p>
    <% end %>

    <% if flash[:success].present? %>
      <p style="color: green"><%= flash[:success] %></p>
    <% end %>

    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#id</th>
          <th scope="col">Nombre del Producto</th>
          <th scope="col">Precio</th>
          <th scope="col">Marca</th>
          <th scope="col">Tipo</th>
          <th scope="col">Imagen</th>
        </tr>
      </thead>
      <tbody>
        <% @productos.each do |producto| %>
          <tr>
            <th scope="row"><%= producto.id %></th>
            <td><%= producto.nombre %></td>
            <td><%= producto.precio %></td>
            <td><%= producto.marca %></td>
            <td><%= producto.tipo %></td>
            <% if producto.img.attached?%>
              <td><%= image_tag(producto.img, style: "width: 100px;") %></td>
            <% else %>
              <td></td>
            <% end %>
            <td>
              <%= link_to "Editar", edit_producto_path(producto), class: "btn btn-primary" %>
              <%= button_to "Eliminar", producto_path(producto), method: :delete, data: { confirm: '¿Estás seguro de querer borrar este artículo?' }, class: "btn btn-danger", remote: true %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p>Por favor, ingrese sesión como administrador</p>
<% end %>

<%= render "welcome/footer" %>

app/views/productos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @producto %>

<div>
  <%= link_to "Edit this producto", edit_producto_path(@producto) %> |
  <%= link_to "Back to productos", productos_path %>

  <%= button_to "Destroy this producto", @producto, method: :delete %>
</div>

app/views/welcome/_navbar.html.erb
<nav class="navbar py-5" style="border-bottom: 1px solid black ;">
        <div class="container-sm mx-auto">
            <%= link_to root_path do %>
                <%= image_tag('main/logo.png', alt: 'Site Logo', style: 'height: 150px;') %>
            <% end %>

            <div class="justify-content-end" id="navbarNav">
                <%= link_to "Productos", verproductos_path, class: "btn btn-nav btn-light btn-outline-dark"  %>
                <%= link_to "Arma tu Skate", armatuskate_path, class: "btn btn-nav btn-light btn-outline-dark"  %>
                <%= link_to "¿Quienes Somos?", quienessomos_path, class: "btn btn-nav btn-light btn-outline-dark"  %>
                <% if user_signed_in? %>
                    <%= link_to "Administrar Productos", productos_path, class: "btn btn-nav btn-secondary btn-outline-dark" %>
                    <%= link_to "Pedidos", pedidos_path, class: "btn btn-nav btn-secondary btn-outline-dark" %>
                <% end %>

            </div>
        </div>
</nav>

app/views/welcome/armatuskate1.html.erb
<%= render "welcome/navbar" %>

<div class='container-xl'>
    <div class='row'>
        <h1>Arma tu skate</h1>
        <h2>Usá nuestra herramienta para construir el skate de tus sueños.</h2>
        <h4>Deberás elegir cada elemento e ingresar tu nombre para almacenar tu pedido.</h4>
        <br>
        <div class="d-flex justify-content-end align-items-center">
            <h3><%= link_to " Comenzar", armatuskate_elegir_path, class: "bi bi-arrow-right-square-fill custom-link" %></h3>   
        </div>
        <div class="d-flex justify-content-end align-items-center">
            <%= image_tag("main/armatuskatebanner", :alt => "...", :class => "img-fluid banner") %>
        </div>
    </div>

</div>

<%= render "welcome/footer" %>

app/views/welcome/index.html.erb
<%= render "welcome/navbar" %>

  <div class="container-xl" style="padding-top: 50px">
    <h1>Arma tu skate</h1>
    
            <% tipo = ["tabla", "trucks", "ruedas", "rulemanes", "lija", "hardware"] %>

            <% tipo.each do |elemento| %> <!--Bucle donde ciclamos el vector de tipo-->

                <% @productos = Producto.where(tipo: elemento) %>
                
                <% if elemento.last == 's' %>
                    <h2 style="padding-top: 2%">Elegí tus <%= elemento %>:</h2>
                <% else %>
                    <h2 style="padding-top: 2%">Elegí tu <%= elemento %>:</h2>
                <% end %>
                
                <div class="row">

                <% @productos.each do |producto| %> <!--Bucle donde ciclamos los productos del tipo-->

                    <div class="photo col-md-3 col-sm-6 mx-auto" style="padding-top: 15px;">
                        <div class="card rounded zoom clickeable" style="width: 100%; text-align: center;" onclick="addToCarro('<%= producto.id %>', '<%= producto.tipo %>', '<%= producto.nombre%>', this);">

                            <img class="card-img-top" src="<%= producto.img.url %>" alt="product_img">

                            <div class="card-body">
                                <h2 style="color: black"> <%= producto.nombre %> </h2>

                                <h3 style="color: black" class="card-subtitle mt-2"> $<%= producto.precio %> </h3>
            
                            </div>
                        </div>
                    </div>

                <% end %>

            <%end%>

            <h5>Seleccionaste: </h5>
            <p id = 'seleccionTabla'><strong>Tabla:</strong> </p>
            <p id = 'seleccionTrucks'><strong>Trucks:</strong> </p>
            <p id = 'seleccionRuedas'><strong>Ruedas:</strong> </p>
            <p id = 'seleccionRulemanes'><strong>Rulemanes:</strong> </p>
            <p id = 'seleccionLija'><strong>Lija:</strong> </p>
            <p id = 'seleccionHardware'><strong>Hardware:</strong> </p>

            <!-- Boton enviar -->
            <%= form_with(url: pedidos_path, method: :post, id: 'myForm') do |form| %>
                <input type="text" id="nombre" name="nombre" placeholder="Ingrese su nombre">
                <input type="hidden" id="carro" name="carro" value="">
                <%= form.submit "Enviar" %>
            <% end %>
        </div>
    </div>

<%= render "welcome/footer" %>

<script>

    var carro = ["", "", "", "", "", ""]; //Es el vector que almacenara un tipo de producto por espacio.

    function addToCarro(productoId, productoTipo, productoNombre, element) { //esta funcion tambien hace que al clickear una carta, esta se resalte.
        if (productoTipo == 'tabla'){
            carro[0] = productoNombre;
            seleccionTabla.innerHTML = '<strong>Tabla:</strong> '+productoNombre;
        } else if (productoTipo == 'trucks'){
            carro[1] = productoNombre;
            seleccionTrucks.innerHTML = '<strong>Trucks:</strong> '+productoNombre;
        } else if (productoTipo == 'ruedas'){
            carro[2] = productoNombre;
            seleccionRuedas.innerHTML = '<strong>Ruedas:</strong> '+productoNombre;
        } else if (productoTipo == 'rulemanes'){
            carro[3] = productoNombre;
            seleccionRulemanes.innerHTML = '<strong>Rulemanes:</strong> '+productoNombre;
        } else if (productoTipo == 'lija') {
            carro[4] = productoNombre;
            seleccionLija.innerHTML = '<strong>Lija:</strong> '+productoNombre;
        } else if (productoTipo == 'hardware') {
            carro[5] = productoNombre;
            seleccionHardware.innerHTML = '<strong>Hardware:</strong> '+productoNombre;
        }

        // Actualizar el campo oculto con el contenido del array carro
        document.getElementById('carro').value = JSON.stringify(carro);

        // Agregar la clase 'clicked' a la carta
        element.classList.add('clicked');
  
        // Eliminar la clase 'clicked' después de 2 segundos
        setTimeout(function() {
            element.classList.remove('clicked');
        }, 1500);

    }

    document.getElementById('myForm').addEventListener('submit', function(event) {
        // Evitar el envío del formulario por defecto
        event.preventDefault();

        // Realizar las validaciones aquí
        if (!validarFormulario()) {
            return;
        }

        // Si las validaciones pasan, enviar el formulario
        this.submit();
    });

    function validarFormulario() {
        var nombre = document.getElementById('nombre').value;
        var carro = JSON.parse(document.getElementById('carro').value);

        // Validar el campo "nombre"
        if (nombre.trim() === '') {
            alert('Por favor, complete el campo Nombre');
            return false;
        }

        // Validar el array "carro"
        for (var i = 0; i < carro.length; i++) {
            if (carro[i] === '') {
            alert('Por favor, complete todos los productos');
            return false;
            }
        }

        return true; // Si todas las validaciones pasan
    }

</script>